apiVersion: v1
kind: Pod
metadata:
  name: mysite
  labels:
    name: mysite
spec:
  containers:
  - name: mysite
    image: acapitainevigs/site
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
